### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Rjchauhan18**
# Fixed :+1: 

- Fixes some syntax errors in contribution.md
- I hope this is what you want to show in the `Contribution.md` file

# Changes 

- Changes in `Contribution.md` file
- Fixes some syntax error.

Hello @0xflotus     
Can you please review it?

### CODE REVIEW

**Review by 0xflotus — APPROVED** [review]

**Comment by Rjchauhan18** [comment]
Hello @0xflotus 
Please tell me if any changes needed to be done .

**Comment by Rjchauhan18** [comment]
Hello @0xflotus 
Can you please tell any changes needed or `can you please merge my PR` ?
**Because i am participating in one event so this is important for me. and If possible can you please label this issue `hacktoberfest`**

**Comment by Rjchauhan18** [comment]
Hello @0xflotus and @KennBro 
Can you please review it?

**Comment by KennBro** [comment]
Oh! Sorry for the delay in replying. This project is a mirror of the real project that is in gitlab. You can perform the PR there

**Pull request closed without merging**
